imprimerid: imprimerid.o
	gcc imprimerid.c -o imprimerid -lpthread
	
nthreads: nthreads.o
	gcc nthreads.c -o nthreads -lpthread
	
simuladorcontagios: simuladorcontagios.o
	gcc simuladorcontagios.c -o simuladorcontagios -lpthread
	
computosobredemanda: computosobredemanda.o
	gcc computosobredemanda.c -o computosobredemanda -lpthread
clean:
	rm -f *.o imprimerid nthreads simuladorcontagios computosobredemanda
